#!/bin/bash
# See skript lisab kasutajale parooli shadow faili sisse
# Failis on parool avatud kujul
#
if [ $# -ne 1 ]; then
    echo "Kasutusjuhend: $0 failinimi"
else
   failinimi=$1
  if [ -f $failinimi -a -r $failinimi ]; then
    echo "fail on korras"
    for rida in $(cat $failinimi)
    do
      #sellega peaks faili sisu olema nähtav, kui fail on kättesaadav ja nüüd echo asemel tuleb teha vajalik skript
      kasutajanimi=$(echo "$rida" | cut -f1 -d:)
      sh lisa_kasutaja $kasutajanimi
      echo "$rida" | chpasswd # antud rida võimaldab kasutajale määrata vastav parool
    done
   else
     echo "probleem failiga $failinimi"
   fi
# parameetrite kontrolli lõpp
fi
